# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"  # Ejemplo para npm (JavaScript)
    directory: "/"           # Directorio donde está el package.json
    schedule:
      interval: "weekly"      # Frecuencia de actualización (daily, weekly, monthly)
    open-pull-requests-limit: 5  # Límite de PRs abiertos a la vez
